Refactor - add sqd providers
squadlocker/sqd-fetch pull request #6
Opened 2019-06-13 10:02 UTC by RutPuselj

2019-06-13 12:06 UTC, IvanAxilis requested changes

2019-06-13 12:06 UTC, IvanAxilis commented on dist/AbstractApi.js
> +        this.sqdProvider = [];
sqdProviders :)

2019-06-13 12:06 UTC, IvanAxilis commented on dist/AbstractApi.js
> +        const index = this.indexOfSqdProvider(provider);
what if there is no such provider

2019-06-14 10:42 UTC, IvanAxilis approved these changes

2019-06-14 10:49 UTC, marinaRupe requested changes

2019-06-14 10:49 UTC, marinaRupe commented on src/AbstractApi.ts
> +  public addSqdProvider(provider:ISqdProvider): AbstractApi {
Add a space before `ISqdProvider` (multiple places)

2019-06-14 10:49 UTC, marinaRupe commented on src/AbstractApi.ts
> +  public deleteSqdProviderByIndex(index:number): boolean {
Add a space before ` number`

2019-06-14 11:34 UTC, marinaRupe approved these changes

2019-06-14 11:57 UTC, merged